In [1]:
import numpy
import pandas

In [2]:
from nba_api.stats.endpoints import scoreboard,scoreboardv2, boxscoresummaryv2, homepageleaders

In [37]:
board = scoreboard.Scoreboard(game_date='2018-12-05')
board2 = scoreboardv2.ScoreboardV2(game_date='2018-12-09')
board2.team_leaders.get_data_frame().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 14 columns):
GAME_ID              8 non-null object
TEAM_ID              8 non-null int64
TEAM_CITY            8 non-null object
TEAM_NICKNAME        8 non-null object
TEAM_ABBREVIATION    8 non-null object
PTS_PLAYER_ID        8 non-null int64
PTS_PLAYER_NAME      8 non-null object
PTS                  8 non-null int64
REB_PLAYER_ID        8 non-null int64
REB_PLAYER_NAME      8 non-null object
REB                  8 non-null int64
AST_PLAYER_ID        8 non-null int64
AST_PLAYER_NAME      8 non-null object
AST                  8 non-null int64
dtypes: int64(7), object(7)
memory usage: 976.0+ bytes

In [8]:
pandas.concat([board2.line_score.get_data_frame(), board2.team_leaders.get_data_frame()], axis=1).set_index('GAME_ID')

,GAME_DATE_EST,GAME_SEQUENCE,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_NAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,PTS_QTR3,...,TEAM_ABBREVIATION,PTS_PLAYER_ID,PTS_PLAYER_NAME,PTS,REB_PLAYER_ID,REB_PLAYER_NAME,REB,AST_PLAYER_ID,AST_PLAYER_NAME,AST
GAME_ID,,,,,,,,,,,,,,,,,,,,,
"(0021800387, 0021800387)",2018-12-09T00:00:00,1,1610612740,NOP,New Orleans,Pelicans,14-14,28,28,35,...,NOP,201950,Jrue Holiday,37,203076,Anthony Davis,9,204025,Tim Frazier,8
"(0021800387, 0021800387)",2018-12-09T00:00:00,1,1610612765,DET,Detroit,Pistons,13-11,20,30,34,...,DET,201933,Blake Griffin,35,203083,Andre Drummond,19,101181,Jose Calderon,9
"(0021800388, 0021800388)",2018-12-09T00:00:00,2,1610612749,MIL,Milwaukee,Bucks,17-8,25,26,28,...,MIL,201572,Brook Lopez,19,203507,Giannis Antetokounmpo,19,203507,Giannis Antetokounmpo,6
"(0021800388, 0021800388)",2018-12-09T00:00:00,2,1610612761,TOR,Toronto,Raptors,21-7,30,19,25,...,TOR,201586,Serge Ibaka,22,202695,Kawhi Leonard,8,200768,Kyle Lowry,7
"(0021800390, 0021800389)",2018-12-09T00:00:00,3,1610612762,UTA,Utah,Jazz,13-14,18,18,36,...,NYK,1628995,Kevin Knox,26,1628995,Kevin Knox,15,203943,Noah Vonleh,9
"(0021800390, 0021800389)",2018-12-09T00:00:00,3,1610612759,SAS,San Antonio,Spurs,13-14,23,31,28,...,CHA,202689,Kemba Walker,25,203469,Cody Zeller,7,202689,Kemba Walker,6
"(0021800389, 0021800390)",2018-12-09T00:00:00,4,1610612766,CHA,Charlotte,Hornets,13-13,27,34,38,...,SAS,201942,DeMar DeRozan,26,200752,Rudy Gay,15,201942,DeMar DeRozan,8
"(0021800389, 0021800390)",2018-12-09T00:00:00,4,1610612752,NYK,New York,Knicks,8-20,24,23,31,...,UTA,1628378,Donovan Mitchell,27,202324,Derrick Favors,8,203497,Rudy Gobert,7

In [41]:
team_leaders = board2.team_leaders.get_data_frame().drop(['GAME_ID','TEAM_ID','TEAM_CITY','TEAM_NICKNAME','TEAM_ABBREVIATION'], axis=1)
scores = board2.line_score.get_data_frame().rename(columns={'PTS': 'TOTAL_PTS', 'AST': 'TOTAL_AST', 'REB': 'TOTAL_REB'})
#both = pandas.merge(board2.line_score.get_data_frame(), board2.team_leaders.get_data_frame(), on=['GAME_ID', 'TEAM_ID'])
combined = pandas.concat([team_leaders, scores], axis=1)
combined.set_index('GAME_ID')

,PTS_PLAYER_ID,PTS_PLAYER_NAME,PTS,REB_PLAYER_ID,REB_PLAYER_NAME,REB,AST_PLAYER_ID,AST_PLAYER_NAME,AST,GAME_DATE_EST,...,PTS_OT8,PTS_OT9,PTS_OT10,TOTAL_PTS,FG_PCT,FT_PCT,FG3_PCT,TOTAL_AST,TOTAL_REB,TOV
GAME_ID,,,,,,,,,,,,,,,,,,,,,
0021800387,201950,Jrue Holiday,37,203076,Anthony Davis,9,204025,Tim Frazier,8,2018-12-09T00:00:00,...,0,0,0,116,0.532,0.870,0.400,27,47,18
0021800387,201933,Blake Griffin,35,203083,Andre Drummond,19,101181,Jose Calderon,9,2018-12-09T00:00:00,...,0,0,0,108,0.439,0.542,0.310,28,47,10
0021800388,201572,Brook Lopez,19,203507,Giannis Antetokounmpo,19,203507,Giannis Antetokounmpo,6,2018-12-09T00:00:00,...,0,0,0,104,0.414,0.850,0.385,22,45,11
0021800388,201586,Serge Ibaka,22,202695,Kawhi Leonard,8,200768,Kyle Lowry,7,2018-12-09T00:00:00,...,0,0,0,99,0.415,0.857,0.341,24,45,11
0021800390,1628995,Kevin Knox,26,1628995,Kevin Knox,15,203943,Noah Vonleh,9,2018-12-09T00:00:00,...,0,0,0,97,0.435,0.737,0.310,23,38,14
0021800390,202689,Kemba Walker,25,203469,Cody Zeller,7,202689,Kemba Walker,6,2018-12-09T00:00:00,...,0,0,0,110,0.528,0.917,0.357,26,46,11
0021800389,201942,DeMar DeRozan,26,200752,Rudy Gay,15,201942,DeMar DeRozan,8,2018-12-09T00:00:00,...,0,0,0,119,0.483,0.852,0.353,19,42,12
0021800389,1628378,Donovan Mitchell,27,202324,Derrick Favors,8,203497,Rudy Gobert,7,2018-12-09T00:00:00,...,0,0,0,107,0.473,0.857,0.500,28,41,17

In [51]:
combined.to_json(orient='records')

'[{"PTS_PLAYER_ID":201950,"PTS_PLAYER_NAME":"Jrue Holiday","PTS":37,"REB_PLAYER_ID":203076,"REB_PLAYER_NAME":"Anthony Davis","REB":9,"AST_PLAYER_ID":204025,"AST_PLAYER_NAME":"Tim Frazier","AST":8,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":1,"GAME_ID":"0021800387","TEAM_ID":1610612740,"TEAM_ABBREVIATION":"NOP","TEAM_CITY_NAME":"New Orleans","TEAM_NAME":"Pelicans","TEAM_WINS_LOSSES":"14-14","PTS_QTR1":28,"PTS_QTR2":28,"PTS_QTR3":35,"PTS_QTR4":25,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":116,"FG_PCT":0.532,"FT_PCT":0.87,"FG3_PCT":0.4,"TOTAL_AST":27,"TOTAL_REB":47,"TOV":18},{"PTS_PLAYER_ID":201933,"PTS_PLAYER_NAME":"Blake Griffin","PTS":35,"REB_PLAYER_ID":203083,"REB_PLAYER_NAME":"Andre Drummond","REB":19,"AST_PLAYER_ID":101181,"AST_PLAYER_NAME":"Jose Calderon","AST":9,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":1,"GAME_ID":"0021800387","TEAM_ID":1610612765,"TEAM_ABBREVIATION":"DET","TEAM_CITY_NAME":"Detroit","TEAM_NAME":"Pistons","TEAM_WINS_LOSSES":"13-11","PTS_QTR1":20,"PTS_QTR2":30,"PTS_QTR3":34,"PTS_QTR4":24,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":108,"FG_PCT":0.439,"FT_PCT":0.542,"FG3_PCT":0.31,"TOTAL_AST":28,"TOTAL_REB":47,"TOV":10},{"PTS_PLAYER_ID":201572,"PTS_PLAYER_NAME":"Brook Lopez","PTS":19,"REB_PLAYER_ID":203507,"REB_PLAYER_NAME":"Giannis Antetokounmpo","REB":19,"AST_PLAYER_ID":203507,"AST_PLAYER_NAME":"Giannis Antetokounmpo","AST":6,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":2,"GAME_ID":"0021800388","TEAM_ID":1610612749,"TEAM_ABBREVIATION":"MIL","TEAM_CITY_NAME":"Milwaukee","TEAM_NAME":"Bucks","TEAM_WINS_LOSSES":"17-8","PTS_QTR1":25,"PTS_QTR2":26,"PTS_QTR3":28,"PTS_QTR4":25,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":104,"FG_PCT":0.414,"FT_PCT":0.85,"FG3_PCT":0.385,"TOTAL_AST":22,"TOTAL_REB":45,"TOV":11},{"PTS_PLAYER_ID":201586,"PTS_PLAYER_NAME":"Serge Ibaka","PTS":22,"REB_PLAYER_ID":202695,"REB_PLAYER_NAME":"Kawhi Leonard","REB":8,"AST_PLAYER_ID":200768,"AST_PLAYER_NAME":"Kyle Lowry","AST":7,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":2,"GAME_ID":"0021800388","TEAM_ID":1610612761,"TEAM_ABBREVIATION":"TOR","TEAM_CITY_NAME":"Toronto","TEAM_NAME":"Raptors","TEAM_WINS_LOSSES":"21-7","PTS_QTR1":30,"PTS_QTR2":19,"PTS_QTR3":25,"PTS_QTR4":25,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":99,"FG_PCT":0.415,"FT_PCT":0.857,"FG3_PCT":0.341,"TOTAL_AST":24,"TOTAL_REB":45,"TOV":11},{"PTS_PLAYER_ID":1628995,"PTS_PLAYER_NAME":"Kevin Knox","PTS":26,"REB_PLAYER_ID":1628995,"REB_PLAYER_NAME":"Kevin Knox","REB":15,"AST_PLAYER_ID":203943,"AST_PLAYER_NAME":"Noah Vonleh","AST":9,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":3,"GAME_ID":"0021800390","TEAM_ID":1610612762,"TEAM_ABBREVIATION":"UTA","TEAM_CITY_NAME":"Utah","TEAM_NAME":"Jazz","TEAM_WINS_LOSSES":"13-14","PTS_QTR1":18,"PTS_QTR2":18,"PTS_QTR3":36,"PTS_QTR4":25,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":97,"FG_PCT":0.435,"FT_PCT":0.737,"FG3_PCT":0.31,"TOTAL_AST":23,"TOTAL_REB":38,"TOV":14},{"PTS_PLAYER_ID":202689,"PTS_PLAYER_NAME":"Kemba Walker","PTS":25,"REB_PLAYER_ID":203469,"REB_PLAYER_NAME":"Cody Zeller","REB":7,"AST_PLAYER_ID":202689,"AST_PLAYER_NAME":"Kemba Walker","AST":6,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":3,"GAME_ID":"0021800390","TEAM_ID":1610612759,"TEAM_ABBREVIATION":"SAS","TEAM_CITY_NAME":"San Antonio","TEAM_NAME":"Spurs","TEAM_WINS_LOSSES":"13-14","PTS_QTR1":23,"PTS_QTR2":31,"PTS_QTR3":28,"PTS_QTR4":28,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":110,"FG_PCT":0.528,"FT_PCT":0.917,"FG3_PCT":0.357,"TOTAL_AST":26,"TOTAL_REB":46,"TOV":11},{"PTS_PLAYER_ID":201942,"PTS_PLAYER_NAME":"DeMar DeRozan","PTS":26,"REB_PLAYER_ID":200752,"REB_PLAYER_NAME":"Rudy Gay","REB":15,"AST_PLAYER_ID":201942,"AST_PLAYER_NAME":"DeMar DeRozan","AST":8,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":4,"GAME_ID":"0021800389","TEAM_ID":1610612766,"TEAM_ABBREVIATION":"CHA","TEAM_CITY_NAME":"Charlotte","TEAM_NAME":"Hornets","TEAM_WINS_LOSSES":"13-13","PTS_QTR1":27,"PTS_QTR2":34,"PTS_QTR3":38,"PTS_QTR4":20,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":119,"FG_PCT":0.483,"FT_PCT":0.852,"FG3_PCT":0.353,"TOTAL_AST":19,"TOTAL_REB":42,"TOV":12},{"PTS_PLAYER_ID":1628378,"PTS_PLAYER_NAME":"Donovan Mitchell","PTS":27,"REB_PLAYER_ID":202324,"REB_PLAYER_NAME":"Derrick Favors","REB":8,"AST_PLAYER_ID":203497,"AST_PLAYER_NAME":"Rudy Gobert","AST":7,"GAME_DATE_EST":"2018-12-09T00:00:00","GAME_SEQUENCE":4,"GAME_ID":"0021800389","TEAM_ID":1610612752,"TEAM_ABBREVIATION":"NYK","TEAM_CITY_NAME":"New York","TEAM_NAME":"Knicks","TEAM_WINS_LOSSES":"8-20","PTS_QTR1":24,"PTS_QTR2":23,"PTS_QTR3":31,"PTS_QTR4":29,"PTS_OT1":0,"PTS_OT2":0,"PTS_OT3":0,"PTS_OT4":0,"PTS_OT5":0,"PTS_OT6":0,"PTS_OT7":0,"PTS_OT8":0,"PTS_OT9":0,"PTS_OT10":0,"TOTAL_PTS":107,"FG_PCT":0.473,"FT_PCT":0.857,"FG3_PCT":0.5,"TOTAL_AST":28,"TOTAL_REB":41,"TOV":17}]'

In [11]:
boxscoresummaryv2.BoxScoreSummaryV2(today_games[0]).line_score.get_data_frame()
#raw_scorelines = [boxscore.line_score.get_data_frame() for boxscore in boxscores]
#scorelines = [scoreline[['TEAM_ABBREVIATION', 'TEAM_CITY_NAME','TEAM_NICKNAME', 'TEAM_WINS_LOSSES','PTS_QTR1', 'PTS_QTR2', 'PTS_QTR3','PTS_QTR4','PTS_OT1','PTS_OT2']] for scoreline in raw_scorelines]
#daily_stats = [boxscore.other_stats.get_data_frame() for boxscore in boxscores]

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_NICKNAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,...,PTS_OT2,PTS_OT3,PTS_OT4,PTS_OT5,PTS_OT6,PTS_OT7,PTS_OT8,PTS_OT9,PTS_OT10,PTS
0,2018-10-28T00:00:00,1,0021800083,1610612751,BKN,Brooklyn,Nets,2-3,29,18,...,0,0,0,0,0,0,0,0,0,47
1,2018-10-28T00:00:00,1,0021800083,1610612744,GSW,Golden State,Warriors,5-1,32,31,...,0,0,0,0,0,0,0,0,0,63

In [78]:
board = scoreboard.Scoreboard(day_offset=-1)
yesterday_games = board.available.get_data_frame()['GAME_ID']

In [79]:
for game in yesterday_games:
    print(game)

0021800036
0021800037
0021800038
0021800039

In [80]:
raw_scorelines = [boxscoresummaryv2.BoxScoreSummaryV2(game).line_score.get_data_frame() for game in yesterday_games]

In [81]:
scorelines = [scoreline[['TEAM_ABBREVIATION', 'TEAM_CITY_NAME','TEAM_NICKNAME', 'TEAM_WINS_LOSSES','PTS_QTR1', 'PTS_QTR2', 'PTS_QTR3','PTS_QTR4','PTS_OT1','PTS_OT2']] for scoreline in raw_scorelines]

In [84]:
raw_stats = [boxscoresummaryv2.BoxScoreSummaryV2(game).other_stats.get_data_frame() for game in yesterday_games]

In [85]:
raw_stats

[  LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  TEAM_CITY  PTS_PAINT  \
 0        00  1610612737               ATL    Atlanta         52
 1        00  1610612739               CLE  Cleveland         44

    PTS_2ND_CHANCE  PTS_FB  LARGEST_LEAD  LEAD_CHANGES  TIMES_TIED  \
 0              11      11            22             3           5
 1              23      10            15             3           5

    TEAM_TURNOVERS  TOTAL_TURNOVERS  TEAM_REBOUNDS  PTS_OFF_TO
 0               0               12              9          15
 1               0               18             10          23  ,
   LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION      TEAM_CITY  PTS_PAINT  \
 0        00  1610612758               SAC     Sacramento         68
 1        00  1610612760               OKC  Oklahoma City         68

    PTS_2ND_CHANCE  PTS_FB  LARGEST_LEAD  LEAD_CHANGES  TIMES_TIED  \
 0               7      18            17             7           7
 1              29      19             3             7           7

    TEAM_TURNOVERS  TOTAL_TURNOVERS  TEAM_REBOUNDS  PTS_OFF_TO
 0               3               20              8          26
 1               0               18             12          28  ,
   LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION     TEAM_CITY  PTS_PAINT  \
 0        00  1610612743               DEN        Denver         48
 1        00  1610612744               GSW  Golden State         44

    PTS_2ND_CHANCE  PTS_FB  LARGEST_LEAD  LEAD_CHANGES  TIMES_TIED  \
 0              11      17            13             8           9
 1              12      11            12             8           9

    TEAM_TURNOVERS  TOTAL_TURNOVERS  TEAM_REBOUNDS  PTS_OFF_TO
 0               2               10             19          12
 1               1               19             11          19  ,
   LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION TEAM_CITY  PTS_PAINT  \
 0        00  1610612746               LAC        LA         64
 1        00  1610612745               HOU   Houston         54

    PTS_2ND_CHANCE  PTS_FB  LARGEST_LEAD  LEAD_CHANGES  TIMES_TIED  \
 0              19      13            11            18           8
 1              10      15             5            18           8

    TEAM_TURNOVERS  TOTAL_TURNOVERS  TEAM_REBOUNDS  PTS_OFF_TO
 0               0               13              5          18
 1               0               12              8          25  ]

In [55]:
from nba_api.stats.endpoints import playbyplayv2, boxscoretraditionalv2 #0021800083

In [95]:
current = playbyplayv2.PlayByPlayV2(game_id='0021800083')

In [96]:
current.get_data_frames()

[Empty DataFrame
 Columns: [GAME_ID, EVENTNUM, EVENTMSGTYPE, EVENTMSGACTIONTYPE, PERIOD, WCTIMESTRING, PCTIMESTRING, HOMEDESCRIPTION, NEUTRALDESCRIPTION, VISITORDESCRIPTION, SCORE, SCOREMARGIN, PERSON1TYPE, PLAYER1_ID, PLAYER1_NAME, PLAYER1_TEAM_ID, PLAYER1_TEAM_CITY, PLAYER1_TEAM_NICKNAME, PLAYER1_TEAM_ABBREVIATION, PERSON2TYPE, PLAYER2_ID, PLAYER2_NAME, PLAYER2_TEAM_ID, PLAYER2_TEAM_CITY, PLAYER2_TEAM_NICKNAME, PLAYER2_TEAM_ABBREVIATION, PERSON3TYPE, PLAYER3_ID, PLAYER3_NAME, PLAYER3_TEAM_ID, PLAYER3_TEAM_CITY, PLAYER3_TEAM_NICKNAME, PLAYER3_TEAM_ABBREVIATION]
 Index: []

 [0 rows x 33 columns],    VIDEO_AVAILABLE_FLAG
 0                     1]

In [56]:
dir(boxscoretraditionalv2)

['BoxScoreTraditionalV2',
 'EndPeriod',
 'EndRange',
 'Endpoint',
 'NBAStatsHTTP',
 'RangeType',
 'StartPeriod',
 'StartRange',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']

In [98]:
boxscoresummaryv2.BoxScoreSummaryV2('0021800083').team_stats.get_data_frame()

AttributeError: 'BoxScoreSummaryV2' object has no attribute 'team_stats'

In [5]:
board = scoreboard.Scoreboard(day_offset=0).line_score.get_data_frame()
board

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,PTS_QTR3,...,PTS_OT8,PTS_OT9,PTS_OT10,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,TOV
0,2018-11-12T00:00:00,1,0021800190,1610612753,ORL,Orlando,6-7,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,2018-11-12T00:00:00,1,0021800190,1610612764,WAS,Washington,3-9,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,2018-11-12T00:00:00,2,0021800191,1610612755,PHI,Philadelphia,8-6,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,2018-11-12T00:00:00,2,0021800191,1610612748,MIA,Miami,5-7,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,2018-11-12T00:00:00,3,0021800192,1610612761,TOR,Toronto,12-1,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,2018-11-12T00:00:00,3,0021800192,1610612740,NOP,New Orleans,6-6,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,2018-11-12T00:00:00,4,0021800193,1610612741,CHI,Chicago,4-9,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,2018-11-12T00:00:00,4,0021800193,1610612742,DAL,Dallas,4-8,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,2018-11-12T00:00:00,5,0021800194,1610612763,MEM,Memphis,7-4,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,2018-11-12T00:00:00,5,0021800194,1610612762,UTA,Utah,6-6,None,None,None,...,None,None,None,None,None,None,None,None,None,None
10,2018-11-12T00:00:00,6,0021800195,1610612750,MIN,Minnesota,4-9,None,None,None,...,None,None,None,None,None,None,None,None,None,None
11,2018-11-12T00:00:00,6,0021800195,1610612751,BKN,Brooklyn,6-7,None,None,None,...,None,None,None,None,None,None,None,None,None,None
12,2018-11-12T00:00:00,7,0021800196,1610612760,OKC,Oklahoma City,7-5,None,None,None,...,None,None,None,None,None,None,None,None,None,None
13,2018-11-12T00:00:00,7,0021800196,1610612756,PHX,Phoenix,2-10,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14,2018-11-12T00:00:00,8,0021800197,1610612758,SAC,Sacramento,7-6,None,None,None,...,None,None,None,None,None,None,None,None,None,None
15,2018-11-12T00:00:00,8,0021800197,1610612759,SAS,San Antonio,7-4,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,2018-11-12T00:00:00,9,0021800198,1610612746,LAC,LA,7-5,None,None,None,...,None,None,None,None,None,None,None,None,None,None
17,2018-11-12T00:00:00,9,0021800198,1610612744,GSW,Golden State,11-2,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [9]:
index_board = board.set_index('TEAM_ID')
index_board.to_dict(orient='index')

{1610612753: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 1,
  'GAME_ID': '0021800190',
  'TEAM_ABBREVIATION': 'ORL',
  'TEAM_CITY_NAME': 'Orlando',
  'TEAM_WINS_LOSSES': '6-7',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612764: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 1,
  'GAME_ID': '0021800190',
  'TEAM_ABBREVIATION': 'WAS',
  'TEAM_CITY_NAME': 'Washington',
  'TEAM_WINS_LOSSES': '3-9',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612755: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 2,
  'GAME_ID': '0021800191',
  'TEAM_ABBREVIATION': 'PHI',
  'TEAM_CITY_NAME': 'Philadelphia',
  'TEAM_WINS_LOSSES': '8-6',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612748: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 2,
  'GAME_ID': '0021800191',
  'TEAM_ABBREVIATION': 'MIA',
  'TEAM_CITY_NAME': 'Miami',
  'TEAM_WINS_LOSSES': '5-7',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612761: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 3,
  'GAME_ID': '0021800192',
  'TEAM_ABBREVIATION': 'TOR',
  'TEAM_CITY_NAME': 'Toronto',
  'TEAM_WINS_LOSSES': '12-1',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612740: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 3,
  'GAME_ID': '0021800192',
  'TEAM_ABBREVIATION': 'NOP',
  'TEAM_CITY_NAME': 'New Orleans',
  'TEAM_WINS_LOSSES': '6-6',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612741: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 4,
  'GAME_ID': '0021800193',
  'TEAM_ABBREVIATION': 'CHI',
  'TEAM_CITY_NAME': 'Chicago',
  'TEAM_WINS_LOSSES': '4-9',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612742: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 4,
  'GAME_ID': '0021800193',
  'TEAM_ABBREVIATION': 'DAL',
  'TEAM_CITY_NAME': 'Dallas',
  'TEAM_WINS_LOSSES': '4-8',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612763: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 5,
  'GAME_ID': '0021800194',
  'TEAM_ABBREVIATION': 'MEM',
  'TEAM_CITY_NAME': 'Memphis',
  'TEAM_WINS_LOSSES': '7-4',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612762: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 5,
  'GAME_ID': '0021800194',
  'TEAM_ABBREVIATION': 'UTA',
  'TEAM_CITY_NAME': 'Utah',
  'TEAM_WINS_LOSSES': '6-6',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612750: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 6,
  'GAME_ID': '0021800195',
  'TEAM_ABBREVIATION': 'MIN',
  'TEAM_CITY_NAME': 'Minnesota',
  'TEAM_WINS_LOSSES': '4-9',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612751: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 6,
  'GAME_ID': '0021800195',
  'TEAM_ABBREVIATION': 'BKN',
  'TEAM_CITY_NAME': 'Brooklyn',
  'TEAM_WINS_LOSSES': '6-7',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612760: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 7,
  'GAME_ID': '0021800196',
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_CITY_NAME': 'Oklahoma City',
  'TEAM_WINS_LOSSES': '7-5',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612756: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 7,
  'GAME_ID': '0021800196',
  'TEAM_ABBREVIATION': 'PHX',
  'TEAM_CITY_NAME': 'Phoenix',
  'TEAM_WINS_LOSSES': '2-10',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612758: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 8,
  'GAME_ID': '0021800197',
  'TEAM_ABBREVIATION': 'SAC',
  'TEAM_CITY_NAME': 'Sacramento',
  'TEAM_WINS_LOSSES': '7-6',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612759: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 8,
  'GAME_ID': '0021800197',
  'TEAM_ABBREVIATION': 'SAS',
  'TEAM_CITY_NAME': 'San Antonio',
  'TEAM_WINS_LOSSES': '7-4',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612746: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 9,
  'GAME_ID': '0021800198',
  'TEAM_ABBREVIATION': 'LAC',
  'TEAM_CITY_NAME': 'LA',
  'TEAM_WINS_LOSSES': '7-5',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None},
 1610612744: {'GAME_DATE_EST': '2018-11-12T00:00:00',
  'GAME_SEQUENCE': 9,
  'GAME_ID': '0021800198',
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_CITY_NAME': 'Golden State',
  'TEAM_WINS_LOSSES': '11-2',
  'PTS_QTR1': None,
  'PTS_QTR2': None,
  'PTS_QTR3': None,
  'PTS_QTR4': None,
  'PTS_OT1': None,
  'PTS_OT2': None,
  'PTS_OT3': None,
  'PTS_OT4': None,
  'PTS_OT5': None,
  'PTS_OT6': None,
  'PTS_OT7': None,
  'PTS_OT8': None,
  'PTS_OT9': None,
  'PTS_OT10': None,
  'PTS': None,
  'FG_PCT': None,
  'FT_PCT': None,
  'FG3_PCT': None,
  'AST': None,
  'REB': None,
  'TOV': None}}

In [68]:
sets = board.data_sets

In [70]:
frames = [set.get_data_frame() for set in sets]

In [99]:
sets = boxscoretraditionalv2.BoxScoreTraditionalV2('0021800083').data_sets

In [100]:
frames = [set.get_data_frame() for set in sets]

In [101]:
frames[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0021800083,1610612744,GSW,Golden State,201142,Kevin Durant,F,,39:08,11.0,...,0.0,8.0,8.0,6.0,1.0,1.0,3.0,0.0,34.0,-2.0
1,0021800083,1610612744,GSW,Golden State,203110,Draymond Green,F,,36:19,4.0,...,1.0,3.0,4.0,13.0,5.0,0.0,1.0,1.0,8.0,-8.0
2,0021800083,1610612744,GSW,Golden State,1627745,Damian Jones,C,,11:35,1.0,...,1.0,0.0,1.0,1.0,1.0,2.0,2.0,4.0,2.0,-6.0
3,0021800083,1610612744,GSW,Golden State,202691,Klay Thompson,G,,35:35,8.0,...,2.0,3.0,5.0,0.0,1.0,1.0,1.0,4.0,18.0,-5.0
4,0021800083,1610612744,GSW,Golden State,201939,Stephen Curry,G,,36:16,11.0,...,1.0,6.0,7.0,3.0,1.0,0.0,2.0,1.0,35.0,11.0
5,0021800083,1610612744,GSW,Golden State,1626172,Kevon Looney,,,12:25,2.0,...,2.0,1.0,3.0,0.0,0.0,0.0,2.0,1.0,4.0,11.0
6,0021800083,1610612744,GSW,Golden State,1628980,Jacob Evans,,,6:27,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
7,0021800083,1610612744,GSW,Golden State,201973,Jonas Jerebko,,,15:21,0.0,...,0.0,6.0,6.0,2.0,0.0,0.0,0.0,0.0,4.0,7.0
8,0021800083,1610612744,GSW,Golden State,2738,Andre Iguodala,,,19:52,2.0,...,3.0,2.0,5.0,2.0,1.0,1.0,0.0,2.0,4.0,3.0
9,0021800083,1610612744,GSW,Golden State,1628035,Alfonzo McKinnie,,,16:53,4.0,...,1.0,4.0,5.0,0.0,1.0,1.0,1.0,2.0,9.0,12.0
10,0021800083,1610612744,GSW,Golden State,1628395,Jordan Bell,,,10:09,1.0,...,1.0,2.0,3.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0
11,0021800083,1610612744,GSW,Golden State,1626188,Quinn Cook,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0021800083,1610612751,BKN,Brooklyn,203925,Joe Harris,F,,29:40,2.0,...,1.0,2.0,3.0,3.0,0.0,0.0,2.0,4.0,7.0,1.0
13,0021800083,1610612751,BKN,Brooklyn,201162,Jared Dudley,F,,21:57,3.0,...,2.0,4.0,6.0,2.0,3.0,0.0,1.0,1.0,6.0,10.0
14,0021800083,1610612751,BKN,Brooklyn,1628386,Jarrett Allen,C,,28:50,5.0,...,0.0,3.0,3.0,4.0,1.0,2.0,1.0,0.0,11.0,14.0
15,0021800083,1610612751,BKN,Brooklyn,1627747,Caris LeVert,G,,30:10,9.0,...,0.0,3.0,3.0,7.0,0.0,0.0,3.0,2.0,23.0,9.0
16,0021800083,1610612751,BKN,Brooklyn,1626156,D'Angelo Russell,G,,29:30,9.0,...,0.0,6.0,6.0,6.0,0.0,1.0,5.0,3.0,25.0,7.0
17,0021800083,1610612751,BKN,Brooklyn,203915,Spencer Dinwiddie,,,23:30,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,12.0,-23.0
18,0021800083,1610612751,BKN,Brooklyn,203459,Allen Crabbe,,,27:43,4.0,...,0.0,5.0,5.0,2.0,0.0,0.0,1.0,5.0,14.0,-4.0
19,0021800083,1610612751,BKN,Brooklyn,1626178,Rondae Hollis-Jefferson,,,17:11,3.0,...,0.0,2.0,2.0,0.0,1.0,0.0,0.0,1.0,7.0,-19.0
20,0021800083,1610612751,BKN,Brooklyn,202334,Ed Davis,,,17:29,2.0,...,1.0,6.0,7.0,1.0,0.0,0.0,0.0,2.0,4.0,-14.0
21,0021800083,1610612751,BKN,Brooklyn,203894,Shabazz Napier,,,14:00,1.0,...,0.0,1.0,1.0,3.0,0.0,0.0,1.0,0.0,5.0,-11.0
22,0021800083,1610612751,BKN,Brooklyn,202702,Kenneth Faried,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0021800083,1610612751,BKN,Brooklyn,1629058,Dzanan Musa,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
board = scoreboardv2.ScoreboardV2(day_offset=1)

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_NAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,...,PTS_OT8,PTS_OT9,PTS_OT10,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,TOV
0,2018-10-29T00:00:00,1,0021800087,1610612757,POR,Portland,Trail Blazers,3-2,None,None,...,None,None,None,None,None,None,None,None,None,None
1,2018-10-29T00:00:00,1,0021800087,1610612754,IND,Indiana,Pacers,4-2,None,None,...,None,None,None,None,None,None,None,None,None,None
2,2018-10-29T00:00:00,2,0021800088,1610612737,ATL,Atlanta,Hawks,2-3,None,None,...,None,None,None,None,None,None,None,None,None,None
3,2018-10-29T00:00:00,2,0021800088,1610612755,PHI,Philadelphia,76ers,3-3,None,None,...,None,None,None,None,None,None,None,None,None,None
4,2018-10-29T00:00:00,3,0021800089,1610612748,MIA,Miami,Heat,3-2,None,None,...,None,None,None,None,None,None,None,None,None,None
5,2018-10-29T00:00:00,3,0021800089,1610612758,SAC,Sacramento,Kings,3-3,None,None,...,None,None,None,None,None,None,None,None,None,None
6,2018-10-29T00:00:00,4,0021800090,1610612752,NYK,New York,Knicks,1-5,None,None,...,None,None,None,None,None,None,None,None,None,None
7,2018-10-29T00:00:00,4,0021800090,1610612751,BKN,Brooklyn,Nets,2-4,None,None,...,None,None,None,None,None,None,None,None,None,None
8,2018-10-29T00:00:00,5,0021800091,1610612741,CHI,Chicago,Bulls,2-4,None,None,...,None,None,None,None,None,None,None,None,None,None
9,2018-10-29T00:00:00,5,0021800091,1610612744,GSW,Golden State,Warriors,6-1,None,None,...,None,None,None,None,None,None,None,None,None,None
10,2018-10-29T00:00:00,6,0021800092,1610612749,MIL,Milwaukee,Bucks,6-0,None,None,...,None,None,None,None,None,None,None,None,None,None
11,2018-10-29T00:00:00,6,0021800092,1610612761,TOR,Toronto,Raptors,6-0,None,None,...,None,None,None,None,None,None,None,None,None,None
12,2018-10-29T00:00:00,7,0021800093,1610612750,MIN,Minnesota,Timberwolves,2-4,None,None,...,None,None,None,None,None,None,None,None,None,None
13,2018-10-29T00:00:00,7,0021800093,1610612747,LAL,Los Angeles,Lakers,2-4,None,None,...,None,None,None,None,None,None,None,None,None,None
14,2018-10-29T00:00:00,8,0021800094,1610612759,SAS,San Antonio,Spurs,3-2,None,None,...,None,None,None,None,None,None,None,None,None,None
15,2018-10-29T00:00:00,8,0021800094,1610612742,DAL,Dallas,Mavericks,2-4,None,None,...,None,None,None,None,None,None,None,None,None,None
16,2018-10-29T00:00:00,9,0021800095,1610612743,DEN,Denver,Nuggets,4-1,None,None,...,None,None,None,None,None,None,None,None,None,None
17,2018-10-29T00:00:00,9,0021800095,1610612740,NOP,New Orleans,Pelicans,4-1,None,None,...,None,None,None,None,None,None,None,None,None,None

In [114]:
dir(board)

['DataSet',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'available',
 'data_sets',
 'east_conf_standings_by_day',
 'endpoint',
 'expected_data',
 'game_header',
 'get_available_data',
 'get_data_frames',
 'get_dict',
 'get_json',
 'get_normalized_dict',
 'get_normalized_json',
 'get_request_url',
 'get_response',
 'last_meeting',
 'line_score',
 'nba_response',
 'series_standings',
 'west_conf_standings_by_day']

In [1]:
import requests
import time
import json
stats_header = {'Host': 'data.nba.com', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive'}
daily_url = 'https://data.nba.com/data/5s/v2015/json/mobile_teams/nba/2018/scores/00_todays_scores.json'
leaders_json = 'https://stats.nba.com/js/data/widgets/scores_leaders.json'
lineups = 'https://stats.nba.com/js/data/widgets/daily_lineups_20181029.json'

In [5]:
result = requests.get('https://stats.nba.com/stats/scoreboardV2?DayOffset=0&LeagueID=00&gameDate=11%2F10%2F2018', headers=stats_header)
print(result.text)

In [107]:
for i in range(0,10000):
    r = requests.get(url, headers=stats_header)
    if r.status_code != 200 and r.url != url:
        print(i)
        break
    time.sleep(1)

KeyboardInterrupt: